server:
  port: 8093
spring:
  jackson:
    default-property-inclusion: NON_NULL
  jersey:
    application-path: /api
  datasource:
    url: jdbc:h2:file:./restshop.db
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: create
      
logging:
  level:
    com:
      roche:
        application: TRACE